classe('Aatrox', lutador_ad).
classe('Ahri', mago).
classe('Ahri', assassino_ap).
classe('Akali', assassino_ap).
classe('Akshan', atirador).
classe('Akshan', assassino_ad).
classe('Alistar', tanque).
classe('Alistar', suporte).
classe('Ambessa', lutador_ad).
classe('Ambessa', assassino_ad).
classe('Amumu', tanque).
classe('Amumu', suporte).
classe('Anivia', mago).
classe('Annie', mago).
classe('Annie', suporte).
classe('Aphelios', atirador).
classe('Ashe', atirador).
classe('Ashe', suporte).
classe('Aurelion Sol', mago).
classe('Aurora', mago).
classe('Aurora', assassino_ap).
classe('Azir', mago).
classe('Azir', atirador).
classe('Bard', suporte).
classe('Bard', mago).
classe('BelVeth', lutador_ad).
classe('Blitzcrank', tanque).
classe('Blitzcrank', suporte).
classe('Brand', mago).
classe('Brand', suporte).
classe('Braum', tanque).
classe('Braum', suporte).
classe('Briar', lutador_ad).
classe('Briar', assassino_ad).
classe('Caitlyn', atirador).
classe('Camille', lutador_ad).
classe('Camille', assassino_ad).
classe('Cassiopeia', mago).
classe('ChoGath', tanque).
classe('ChoGath', mago).
classe('Corki', mago).
classe('Corki', atirador).
classe('Darius', lutador_ad).
classe('Darius', tanque).
classe('Diana', assassino_ap).
classe('Diana', lutador_ap).
classe('Dr.Mundo', tanque).
classe('Dr.Mundo', lutador_ad).
classe('Draven', atirador).
classe('Ekko', mago).
classe('Ekko', assassino_ap).
classe('Elise', mago).
classe('Elise', assassino_ap).
classe('Evelynn', mago).
classe('Evelynn', assassino_ap).
classe('Ezreal', atirador).
classe('Ezreal', mago).
classe('Fiddlesticks', mago).
classe('Fiddlesticks', suporte).
classe('Fiora', lutador_ad).
classe('Fiora', assassino_ad).
classe('Fizz', lutador_ap).
classe('Fizz', assassino_ap).
classe('Galio', tanque).
classe('Galio', mago).
classe('Gangplank', lutador_ap).
classe('Garen', lutador_ap).
classe('Garen', tanque).
classe('Gnar', lutador_ad).
classe('Gnar', tanque).
classe('Gragas', lutador_ap).
classe('Gragas', mago).
classe('Graves', atirador).
classe('Gwen', lutador_ap).
classe('Hecarim', lutador_ap).
classe('Hecarim', tanque).
classe('Heimerdinger', mago).
classe('Heimerdinger', suporte).
classe('Hwei', mago).
classe('Hwei', suporte).
classe('Illaoi', lutador_ap).
classe('Illaoi', tanque).
classe('Irelia', lutador_ad).
classe('Irelia', assassino_ad).
classe('Ivern', mago).
classe('Ivern', suporte).
classe('Janna', mago).
classe('Janna', suporte).
classe('Jarvan IV', lutador_ad).
classe('Jarvan IV', tanque).
classe('Jax', lutador_ad).
classe('Jayce', atirador).
classe('Jayce', lutador_ad).
classe('Jhin', mago).
classe('Jhin', atirador).
classe('Jinx', atirador).
classe('KSante', tanque).
classe('KSante', lutador_ad).
classe('Kaisa', mago).
classe('Kaisa', atirador).
classe('Kalista', atirador).
classe('Karma', mago).
classe('Karma', suporte).
classe('Karthus', mago).
classe('Kassadin', mago).
classe('Kassadin', assassino_ap).
classe('Katarina', mago).
classe('Katarina', assassino_ap).
classe('Kayle', mago).
classe('Kayle', atirador).
classe('Kayn', lutador_ad).
classe('Kayn', assassino_ad).
classe('Kennen', mago).
classe('Khazix', assassino_ad).
classe('Kindred', atirador).
classe('Kled', lutador_ad).
classe('KogMaw', mago).
classe('KogMaw', atirador).
classe('Leblanc', mago).
classe('Leblanc', assassino_ap).
classe('Lee Sin', lutador_ad).
classe('Lee Sin', assassino_ad).
classe('Leona', tanque).
classe('Leona', suporte).
classe('Lillia', mago).
classe('Lillia', lutador_ap).
classe('Lissandra', mago).
classe('Lucian', atirador).
classe('Lucian', assassino_ad).
classe('Lulu', mago).
classe('Lulu', suporte).
classe('Lux', mago).
classe('Lux', suporte).
classe('Malphite', mago).
classe('Malphite', tanque).
classe('Malzahar', mago).
classe('Maokai', tanque).
classe('Maokai', suporte).
classe('Master Yi', assassino_ad).
classe('Master Yi', lutador_ad).
classe('Mel', mago).
classe('Mel', suporte).
classe('Milio', mago).
classe('Milio', suporte).
classe('Miss Fortune', atirador).
classe('Miss Fortune', mago).
classe('Mordekaiser', mago).
classe('Mordekaiser', lutador_ap).
classe('Morgana', mago).
classe('Morgana', suporte).
classe('Naafiri', assassino_ap).
classe('Naafiri', lutador_ap).
classe('Nami', suporte).
classe('Nami', mago).
classe('Nasus', lutador_ad).
classe('Nasus', tanque).
classe('Nautilus', tanque).
classe('Nautilus', suporte).
classe('Neeko', mago).
classe('Neeko', suporte).
classe('Nidalee', mago).
classe('Nidalee', assassino_ap).
classe('Nidalee', meele).
classe('Nilah', lutador_ad).
classe('Nilah', assassino_ad).
classe('Nocturne', lutador_ad).
classe('Nocturne', assassino_ad).
classe('Nunu e Willump', mago).
classe('Nunu e Willump', tanque).
classe('Olaf', lutador_ad).
classe('Olaf', tanque).
classe('Orianna', mago).
classe('Orianna', suporte).
classe('Ornn', tanque).
classe('Pantheon', lutador_ap).
classe('Pantheon', assassino_ap).
classe('Poppy', tanque).
classe('Poppy', lutador_ap).
classe('Pyke', suporte).
classe('Pyke', assassino_ad).
classe('Qiyana', assassino_ap).
classe('Quinn', atirador).
classe('Quinn', assassino_ad).
classe('Rakan', suporte).
classe('Rammus', tanque).
classe('RekSai', lutador_ad).
classe('RekSai', tanque).
classe('Rell', tanque).
classe('Rell', suporte).
classe('Renata Glasc', mago).
classe('Renata Glasc', suporte).
classe('Renekton', lutador_ad).
classe('Renekton', tanque).
classe('Rengar', assassino_ad).
classe('Rengar', lutador_ad).
classe('Riven', lutador_ap).
classe('Riven', assassino_ap).
classe('Rumble', mago).
classe('Rumble', lutador_ap).
classe('Ryze', mago).
classe('Samira', atirador).
classe('Samira', assassino_ad).
classe('Sejuani', tanque).
classe('Senna', suporte).
classe('Senna', atirador).
classe('Seraphine', mago).
classe('Seraphine', suporte).
classe('Sett', lutador_ad).
classe('Sett', tanque).
classe('Shaco', assassino_ad).
classe('Shen', tanque).
classe('Shyvana', lutador_ap).
classe('Shyvana', mago).
classe('Singed', mago).
classe('Singed', tanque).
classe('Sion', tanque).
classe('Sion', lutador_ap).
classe('Sivir', atirador).
classe('Skarner', tanque).
classe('Skarner', lutador_ad).
classe('Smolder', atirador).
classe('Smolder', mago).
classe('Sona', suporte).
classe('Sona', mago).
classe('Soraka', mago).
classe('Soraka', suporte).
classe('Swain', mago).
classe('Swain', suporte).
classe('Sylas', mago).
classe('Sylas', assassino_ap).
classe('Syndra', mago).
classe('Tahm Kench', tanque).
classe('Tahm Kench', suporte).
classe('Taliyah', mago).
classe('Taliyah', suporte).
classe('Talon', assassino_ap).
classe('Taric', suporte).
classe('Taric', tanque).
classe('Teemo', atirador).
classe('Teemo', mago).
classe('Thresh', tanque).
classe('Thresh', suporte).
classe('Tristana', atirador).
classe('Tristana', assassino_ad).
classe('Trundle', lutador_ad).
classe('Trundle', tanque).
classe('Tryndamere', lutador_ad).
classe('Tryndamere', assassino_ad).
classe('Twisted Fate', mago).
classe('Twisted Fate', atirador).
classe('Twitch', atirador).
classe('Twitch', assassino_ad).
classe('Udyr', tanque).
classe('Udyr', lutador_ad).
classe('Urgot', lutador_ap).
classe('Urgot', tanque).
classe('Varus', mago).
classe('Varus', atirador).
classe('Vayne', atirador).
classe('Vayne', assassino_ad).
classe('Veigar', mago).
classe('VelKoz', mago).
classe('VelKoz', suporte).
classe('Vex', mago).
classe('Vi', assassino_ad).
classe('Vi', lutador_ad).
classe('Viego', lutador_ad).
classe('Viego', assassino_ad).
classe('Viktor', mago).
classe('Vladimir', mago).
classe('Vladimir', lutador_ap).
classe('Volibear', lutador_ad).
classe('Volibear', tanque).
classe('Warwick', lutador_ad).
classe('Warwick', tanque).
classe('Wukong', lutador_ad).
classe('Wukong', tanque).
classe('Xayah', atirador).
classe('Xerath', mago).
classe('Xerath', suporte).
classe('XinZhao', lutador_ad).
classe('XinZhao', tanque).
classe('Yasuo', lutador_ad).
classe('Yasuo', assassino_ad).
classe('Yone', lutador_ad).
classe('Yone', assassino_ad).
classe('Yorick', lutador_ap).
classe('Yorick', tanque).
classe('Yuumi', mago).
classe('Yuumi', suporte).
classe('Zac', tanque).
classe('Zac', lutador_ap).
classe('Zed', assassino_ad).
classe('Zeri', atirador).
classe('Ziggs', mago).
classe('Zilean', suporte).
classe('Zilean', mago).
classe('Zoe', mago).
classe('Zyra', mago).
classe('Zyra', suporte).