ranged_type('Aatrox', melee).
ranged_type('Ahri', ranged).
ranged_type('Akali', melee).
ranged_type('Akshan', ranged).
ranged_type('Alistar', melee).
ranged_type('Ambessa', melee).
ranged_type('Amumu', melee).
ranged_type('Anivia', ranged).
ranged_type('Annie', ranged).
ranged_type('Aphelios', ranged).
ranged_type('Ashe', ranged).
ranged_type('Aurelion Sol', ranged).
ranged_type('Aurora', ranged).
ranged_type('Azir', ranged).
ranged_type('Bard', ranged).
ranged_type('BelVeth', melee).
ranged_type('Blitzcrank', melee).
ranged_type('Brand', ranged).
ranged_type('Braum', melee).
ranged_type('Briar', melee).
ranged_type('Caitlyn', ranged).
ranged_type('Camille', melee).
ranged_type('Cassiopeia', ranged).
ranged_type('ChoGath', melee).
ranged_type('Corki', ranged).
ranged_type('Darius', melee).
ranged_type('Diana', melee).
ranged_type('Dr.Mundo', melee).
ranged_type('Draven', ranged).
ranged_type('Ekko', melee).
ranged_type('Elise', melee).
ranged_type('Elise', ranged).
ranged_type('Evelynn', melee).
ranged_type('Ezreal', ranged).
ranged_type('Fiddlesticks', ranged).
ranged_type('Fiora', melee).
ranged_type('Fizz', melee).
ranged_type('Galio', melee).
ranged_type('Gangplank', melee).
ranged_type('Garen', melee).
ranged_type('Gnar', ranged).
ranged_type('Gnar', melee).
ranged_type('Gragas', ranged).
ranged_type('Graves', melee).
ranged_type('Gwen', melee).
ranged_type('Hecarim', melee).
ranged_type('Heimerdinger', ranged).
ranged_type('Hwei', ranged).
ranged_type('Illaoi', melee).
ranged_type('Irelia', melee).
ranged_type('Ivern', ranged).
ranged_type('Janna', ranged).
ranged_type('Jarvan IV', melee).
ranged_type('Jax', melee).
ranged_type('Jayce', melee).
ranged_type('Jayce', ranged).
ranged_type('Jhin', ranged).
ranged_type('Jinx', ranged).
ranged_type('KSante', melee).
ranged_type('Kaisa', ranged).
ranged_type('Kalista', ranged).
ranged_type('Karma', ranged).
ranged_type('Karthus', ranged).
ranged_type('Kassadin', melee).
ranged_type('Katarina', melee).
ranged_type('Kayle', ranged).
ranged_type('Kayle', melee).
ranged_type('Kayn', melee).
ranged_type('Kennen', ranged).
ranged_type('Khazix', melee).
ranged_type('Kindred', ranged).
ranged_type('Kled', melee).
ranged_type('KogMaw', ranged).
ranged_type('Leblanc', ranged).
ranged_type('Lee Sin', melee).
ranged_type('Leona', melee).
ranged_type('Lillia', melee).
ranged_type('Lissandra', ranged).
ranged_type('Lucian', ranged).
ranged_type('Lulu', ranged).
ranged_type('Lux', ranged).
ranged_type('Malphite', ranged).
ranged_type('Malzahar', ranged).
ranged_type('Maokai', melee).
ranged_type('Master Yi', melee).
ranged_type('Mel', ranged).
ranged_type('Milio', ranged).
ranged_type('Miss Fortune', ranged).
ranged_type('Mordekaiser', melee).
ranged_type('Morgana', ranged).
ranged_type('Naafiri', melee).
ranged_type('Nami', ranged).
ranged_type('Nasus', melee).
ranged_type('Nautilus', melee).
ranged_type('Neeko', ranged).
ranged_type('Nidalee', ranged).
ranged_type('Nidalee', meele).
ranged_type('Nilah', melee).
ranged_type('Nocturne', melee).
ranged_type('Nunu e Willump', melee).
ranged_type('Olaf', melee).
ranged_type('Orianna', ranged).
ranged_type('Ornn', melee).
ranged_type('Pantheon', melee).
ranged_type('Poppy', melee).
ranged_type('Pyke', melee).
ranged_type('Qiyana', melee).
ranged_type('Quinn', ranged).
ranged_type('Rakan', melee).
ranged_type('Rammus', melee).
ranged_type('RekSai', melee).
ranged_type('Rell', melee).
ranged_type('Renata Glasc', ranged).
ranged_type('Renekton', melee).
ranged_type('Rengar', melee).
ranged_type('Riven', melee).
ranged_type('Rumble', melee).
ranged_type('Ryze', ranged).
ranged_type('Samira', ranged).
ranged_type('Sejuani', melee).
ranged_type('Senna', ranged).
ranged_type('Seraphine', ranged).
ranged_type('Sett', melee).
ranged_type('Shaco', melee).
ranged_type('Shen', melee).
ranged_type('Shyvana', melee).
ranged_type('Singed', melee).
ranged_type('Sion', melee).
ranged_type('Sivir', ranged).
ranged_type('Skarner', melee).
ranged_type('Smolder', ranged).
ranged_type('Sona', ranged).
ranged_type('Soraka', ranged).
ranged_type('Swain', ranged).
ranged_type('Sylas', melee).
ranged_type('Syndra', ranged).
ranged_type('Tahm Kench', melee).
ranged_type('Taliyah', ranged).
ranged_type('Talon', melee).
ranged_type('Taric', melee).
ranged_type('Teemo', ranged).
ranged_type('Thresh', ranged).
ranged_type('Tristana', ranged).
ranged_type('Trundle', melee).
ranged_type('Tryndamere', melee).
ranged_type('Twisted Fate', ranged).
ranged_type('Twitch', ranged).
ranged_type('Udyr', melee).
ranged_type('Urgot', melee).
ranged_type('Varus', ranged).
ranged_type('Vayne', ranged).
ranged_type('Veigar', ranged).
ranged_type('VelKoz', ranged).
ranged_type('Vex', ranged).
ranged_type('Vi', melee).
ranged_type('Viego', melee).
ranged_type('Viktor', ranged).
ranged_type('Vladimir', ranged).
ranged_type('Volibear', melee).
ranged_type('Warwick', melee).
ranged_type('Wukong', melee).
ranged_type('Xayah', ranged).
ranged_type('Xerath', ranged).
ranged_type('XinZhao', melee).
ranged_type('Yasuo', melee).
ranged_type('Yone', melee).
ranged_type('Yorick', melee).
ranged_type('Yuumi', ranged).
ranged_type('Zac', melee).
ranged_type('Zed', melee).
ranged_type('Zeri', ranged).
ranged_type('Ziggs', ranged).
ranged_type('Zilean', ranged).
ranged_type('Zoe', ranged).
ranged_type('Zyra', ranged).